### ISSUE TITLE
Auto reload on change

### ISSUE THREAD

**Issue by RuudBurger** [athombv/athom-cli#7]
For development now you have to constantly do `athom project --run` then quit and repeat. Each change you want to test takes 30 seconds or more. Not really efficient. Combined with a proper feedback system (https://github.com/athombv/homey/issues/171) this would help alot.

I'm wondering how you guys use this tool yourself, or that you develop directly on Homey (if so please tell me how)?

**Comment by WeeJeWel** [comment]
30 seconds is a long time. It usually takes me around 6s. Do you have many node_modules, or any other large files?

We're planning on uploading through USB in the future.

**Comment by RuudBurger** [comment]
Only the request library. 
But I think you should let the apps be more "node" then the custom packaging you're using now. Because I need to copy the request library in node_modules manually instead of the default way using `npm install request --save`. By doing this, you can take advantage of the packages.json and module loading (install only when required packages have changed).

**Comment by WeeJeWel** [comment]
You can of course always add a package.json to your project to manage your packages.

Due to the nature of Homey, it's really hard to integrate with npm (and next to it being actually slower, it's a big security flaw as well)
